name: logger
home: https://github.com/drycc/logger
apiVersion: v2
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
description: Log buffer used by Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
