imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# Maximum lines of recent log file to display
logsMaximumLines: 3000
# Maximum timeout for follow logs
logsMaximumTimeout: 300

## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 50Mi
  # requests:
  #   cpu: 100m
  #   memory: 30Mi

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  type: ""
  extraMatchLabels:
    security: "drycc-security"

podAntiAffinityPreset:
  type: "soft"
  extraMatchLabels:
    app: "drycc-logger"

# logger replicas
replicas: 1

# Service
service:
  # Provide any additional service annotations
  annotations: {}

# external valkey configuration
valkeyUrl: ""

valkey:
  enabled: true

global:
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
