imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# limitsCpu: "100m"
# limitsMemory: "50Mi"
# Maximum lines of recent log file to display
logsMaximumLines: 300
# Maximum timeout for follow logs
logsMaximumTimeout: 300

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  key: "security"
  type: ""
  values:
  - "drycc-security"

podAntiAffinityPreset:
  key: "app"
  type: "soft"
  values:
  - "drycc-logger"
# logger replicas
replicas: 1
# Service
service:
  # Provide any additional service annotations
  annotations: {}

redis:
  replicas: 1

global:
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
  # Set the location of Workflow's logger-specific Redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in loggerRedis section)
  redisLocation: "on-cluster"
