org: "drycc"
pull_policy: "Always"
docker_tag: "canary"
docker_registry: ""
# limits_cpu: "100m"
# limits_memory: "50Mi"

nsqd:
  replicas: 1
  tcp_port: 4150
  http_port: 4151

redis:
  replicas: 1
  port: "6379"

global:
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  cluster_domain: "cluster.local"
  # Set the location of Workflow's logger-specific Redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in loggerRedis section)
  redis_location: "on-cluster"
