apiVersion: v1
kind: Service
metadata:
  name: drycc-logger
  labels:
    heritage: drycc
    app: drycc-logger
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: drycc-logger
