apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: drycc-logger
  namespace: drycc
spec:
  podSelector:
    matchLabels:
      app: drycc-logger
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
        podSelector:
          matchLabels:
            app: drycc-controller-api
