{{ $nsqdNodeCount := .Values.nsqd.replicas | int }}
{{ $redisNodeCount := .Values.redis.replicas | int }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-logger
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-logger
  template:
    metadata:
      labels:
        app: drycc-logger
    spec:
      containers:
      - name: drycc-logger
        image: {{.Values.docker_registry}}{{.Values.org}}/logger:{{.Values.docker_tag}}
        imagePullPolicy: {{.Values.pull_policy}}
        env:
        - name: STORAGE_ADAPTER
          value: redis
{{ if eq .Values.global.logger_redis_location "on-cluster"}}
        - name: DRYCC_LOGGER_REDIS_ADDRS
          value: "{{range $i := until $redisNodeCount}}drycc-logger-redis-{{$i}}.drycc-logger-redis.{{$.Release.Namespace}}.svc.{{$.Values.global.cluster_domain}}:{{$.Values.redis.port}}{{if lt (add 1 $i) $redisNodeCount}},{{end}}{{end}}"
{{- else if eq .Values.global.logger_redis_location "off-cluster" }}
        - name: DRYCC_LOGGER_REDIS_ADDRS
          valueFrom:
            secretKeyRef:
              name: logger-redis-creds
              key: addrs
{{- end }}
        - name: DRYCC_LOGGER_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logger-redis-creds
              key: password
        - name: DRYCC_NSQD_ADDRS
          value: "{{range $i := until $nsqdNodeCount}}drycc-nsqd-{{$i}}.drycc-nsqd.{{$.Release.Namespace}}.svc.{{$.Values.global.cluster_domain}}:{{$.Values.nsqd.tcp_port}}{{if lt (add 1 $i) $nsqdNodeCount}},{{end}}{{end}}"
        ports:
        - containerPort: 8088
          name: http
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
