apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-logger
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-logger
  template:
    metadata:
      labels:
        app: drycc-logger
    spec:
      {{- include "common.affinities.pods.soft" (dict "key" "app" "values" (list "drycc-logger")) | indent 6 }}
      initContainers:
      - name: drycc-logger-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -a
          - $(DRYCC_REDIS_ADDRS)
        env:
        - name: DRYCC_REDIS_ADDRS
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: addrs
      containers:
      - name: drycc-logger
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/logger:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        env:
        - name: STORAGE_ADAPTER
          value: redis
        - name: DRYCC_REDIS_ADDRS
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: addrs
        - name: DRYCC_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: password
        ports:
        - containerPort: 8088
          name: http
{{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
{{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
{{- end}}
{{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
{{- end}}
{{- end}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
