apiVersion: v1
kind: Service
metadata:
  name: drycc-logger
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
    app: drycc-logger
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: drycc-logger
