matrix:
  platform:
  - linux/amd64
  - linux/arm64

platform: ${platform}

labels:
  type: exec

pipeline:
- name: test-linux
  image: bash
  commands:
  - make bootstrap test test-cover
  - curl -s https://codecov.io/bash | bash
  secrets:
  - dev_registry
  - codecov_token
  when:
    event:
    - push
    - tag
    - pull_request
